title: Jek
email: hello@jek.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter: tbutler0x90
github:  tcbutler320
mail: developer.tbutler@gmail.com
linkedin: tyler-b-a700a1aa

# site settings 
contact: true
about: true
version: v1.1.0

# Theme settings 

edit-date: false # show the date of last edit on pages
default-theme: sandcastle # pick which theme loads by default

# post settings 

tags: foo bar
# development settings 

developer-controls: false # show developer specefic tips

# Build settings
theme: jek
plugins:
  - jekyll-feed


markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class : 'syntax'

